packages:
  - "infra"
overrides:
  '@codemirror/state': 6.7.3
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@ruxt/core@0.1.0'
  - '@ruxt/editor@0.1.0'
